//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SQLDB : DbContext
    {
        public SQLDB()
            : base("name=SQLDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SysDepartment> SysDepartments { get; set; }
        public DbSet<SysDeptUser> SysDeptUsers { get; set; }
        public DbSet<SysRole> SysRoles { get; set; }
        public DbSet<SysRoleUser> SysRoleUsers { get; set; }
        public DbSet<SysUser> SysUsers { get; set; }
        public DbSet<WfDelegate> WfDelegates { get; set; }
        public DbSet<WfInstance> WfInstances { get; set; }
        public DbSet<WfNode> WfNodes { get; set; }
        public DbSet<WfProcess> WfProcesses { get; set; }
        public DbSet<WfRepository> WfRepositories { get; set; }
        public DbSet<WfSerialNum> WfSerialNums { get; set; }
        public DbSet<WfTask> WfTasks { get; set; }
        public DbSet<WfTransition> WfTransitions { get; set; }
        public DbSet<WfVar> WfVars { get; set; }
    }
}
