//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUser
    {
        public SysUser()
        {
            this.SysDeptUsers = new HashSet<SysDeptUser>();
            this.SysRoleUsers = new HashSet<SysRoleUser>();
        }
    
        public System.Guid UserGuid { get; set; }
        public string UserID { get; set; }
        public string UserPwd { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> UserSex { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<SysDeptUser> SysDeptUsers { get; set; }
        public virtual ICollection<SysRoleUser> SysRoleUsers { get; set; }
    }
}
