//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WfInstance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WfInstance()
        {
            this.WfNode = new HashSet<WfNode>();
            this.WfTask = new HashSet<WfTask>();
            this.WfTransition = new HashSet<WfTransition>();
            this.WfVar = new HashSet<WfVar>();
        }
    
        public System.Guid InstanceGuid { get; set; }
        public System.Guid ProcessGuid { get; set; }
        public string ProcessVersion { get; set; }
        public string InstanceTitle { get; set; }
        public byte InstanceStatus { get; set; }
        public Nullable<System.Guid> CurrentTask { get; set; }
        public System.Guid Originator { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.Guid> Terminator { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public byte[] Stamp { get; set; }
    
        public virtual WfRepository WfRepository { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfNode> WfNode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfTask> WfTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfTransition> WfTransition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfVar> WfVar { get; set; }
    }
}
