//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WfInstance
    {
        public WfInstance()
        {
            this.WfNodes = new HashSet<WfNode>();
            this.WfTasks = new HashSet<WfTask>();
            this.WfTransitions = new HashSet<WfTransition>();
            this.WfVars = new HashSet<WfVar>();
        }
    
        public System.Guid InstanceGuid { get; set; }
        public System.Guid RepoGuid { get; set; }
        public string InstanceTitle { get; set; }
        public byte InstanceStatus { get; set; }
        public Nullable<System.Guid> CurrentTask { get; set; }
        public System.Guid Originator { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.Guid> Terminator { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public byte[] Stamp { get; set; }
    
        public virtual WfRepository WfRepository { get; set; }
        public virtual ICollection<WfNode> WfNodes { get; set; }
        public virtual ICollection<WfTask> WfTasks { get; set; }
        public virtual ICollection<WfTransition> WfTransitions { get; set; }
        public virtual ICollection<WfVar> WfVars { get; set; }
    }
}
