//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WfNode
    {
        public WfNode()
        {
            this.WfTasks = new HashSet<WfTask>();
        }
    
        public System.Guid NodeGuid { get; set; }
        public System.Guid InstanceGuid { get; set; }
        public string StepDefID { get; set; }
        public byte NodeType { get; set; }
        public Nullable<System.Guid> RawNodeGuid { get; set; }
        public Nullable<System.Guid> Sponsor { get; set; }
        public Nullable<double> PassRate { get; set; }
        public Nullable<byte> AddSign { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual WfInstance WfInstance { get; set; }
        public virtual ICollection<WfTask> WfTasks { get; set; }
    }
}
