//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WfRepository
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WfRepository()
        {
            this.WfInstance = new HashSet<WfInstance>();
        }
    
        public System.Guid RepoGuid { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public byte[] Stamp { get; set; }
        public string Version { get; set; }
        public string BpmFile { get; set; }
        public string BpmPath { get; set; }
        public string BpmContent { get; set; }
        public Nullable<System.Guid> ProcessGuid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfInstance> WfInstance { get; set; }
        public virtual WfProcess WfProcess { get; set; }
    }
}
