//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WfTask
    {
        public System.Guid TaskGuid { get; set; }
        public System.Guid InstanceGuid { get; set; }
        public System.Guid NodeGuid { get; set; }
        public string TaskTitle { get; set; }
        public Nullable<byte> TaskType { get; set; }
        public byte TaskStatus { get; set; }
        public System.Guid TaskOwner { get; set; }
        public System.Guid TaskActor { get; set; }
        public byte[] Stamp { get; set; }
    
        public virtual WfInstance WfInstance { get; set; }
        public virtual WfNode WfNode { get; set; }
    }
}
