//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WfTransition
    {
        public System.Guid TransferGuid { get; set; }
        public System.Guid InstanceGuid { get; set; }
        public byte TransferType { get; set; }
        public string ConditionResult { get; set; }
        public System.Guid SourceGuid { get; set; }
        public System.Guid TargetGuid { get; set; }
        public byte[] Stamp { get; set; }
    
        public virtual WfInstance WfInstance { get; set; }
    }
}
