//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SQLDB : DbContext
    {
        public SQLDB()
            : base("name=SQLDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SysDepartment> SysDepartment { get; set; }
        public virtual DbSet<SysDeptUser> SysDeptUser { get; set; }
        public virtual DbSet<SysRole> SysRole { get; set; }
        public virtual DbSet<SysRoleUser> SysRoleUser { get; set; }
        public virtual DbSet<SysUser> SysUser { get; set; }
        public virtual DbSet<WfDelegate> WfDelegate { get; set; }
        public virtual DbSet<WfInstance> WfInstance { get; set; }
        public virtual DbSet<WfNode> WfNode { get; set; }
        public virtual DbSet<WfProcess> WfProcess { get; set; }
        public virtual DbSet<WfRepository> WfRepository { get; set; }
        public virtual DbSet<WfSerialNum> WfSerialNum { get; set; }
        public virtual DbSet<WfTask> WfTask { get; set; }
        public virtual DbSet<WfTransition> WfTransition { get; set; }
        public virtual DbSet<WfVar> WfVar { get; set; }
    }
}
