//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class WfDelegate
    {
        public System.Guid DelegateGuid { get; set; }
        public System.Guid PrincipalGuid { get; set; }
        public System.Guid TrusteeGuid { get; set; }
        public byte DelegateType { get; set; }
        public string ObjectGuids { get; set; }
        public byte Status { get; set; }
        public System.DateTime EffectTime { get; set; }
        public Nullable<System.DateTime> ExpireTime { get; set; }
    }
}
