//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class WfNode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WfNode()
        {
            this.WfTask = new HashSet<WfTask>();
        }
    
        public System.Guid NodeGuid { get; set; }
        public System.Guid InstanceGuid { get; set; }
        public string StepDefID { get; set; }
        public byte NodeType { get; set; }
        public Nullable<System.Guid> RawNodeGuid { get; set; }
        public Nullable<System.Guid> Sponsor { get; set; }
        public Nullable<double> PassRate { get; set; }
        public Nullable<byte> AddSign { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual WfInstance WfInstance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfTask> WfTask { get; set; }
    }
}
